doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_id: 'App\Course\Infrastructure\Persistence\Doctrine\Type\UserIdType'
            course_id: 'App\Course\Infrastructure\Persistence\Doctrine\Type\CourseIdType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Course\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Course/Infrastructure/Persistence/Doctrine/mapping'
                prefix: 'App\Course\Domain\Entity'
                alias: App\Course\Domain\Entity
            App\Course\Domain\ValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Course/Infrastructure/Persistence/Doctrine/mappingVO'
                prefix: 'App\Course\Domain\ValueObject'
                alias: App\Course\Domain\ValueObject

