doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_id: 'App\Shared\Infrastructure\Persistence\Doctrine\Type\UserIdType'
            course_id: 'App\Course\Infrastructure\Persistence\Doctrine\Type\CourseIdType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Shared\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/mapping'
                prefix: 'App\Shared\Domain\Entity'
                alias: App\Shared\Domain\Entity
            App\Shared\Domain\ValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/mappingVO'
                prefix: 'App\Shared\Domain\ValueObject'
                alias: App\Shared\Domain\ValueObject
            App\Course\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Course/Infrastructure/Persistence/Doctrine/mapping'
                prefix: 'App\Course\Domain\Entity'
                alias: App\Course\Domain\Entity
            App\Course\Domain\ValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Course/Infrastructure/Persistence/Doctrine/mappingVO'
                prefix: 'App\Course\Domain\ValueObject'
                alias: App\Course\Domain\ValueObject
            App\Admin\Domain\Entity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Admin/Infrastructure/Persistence/Doctrine/mapping'
                prefix: 'App\Admin\Domain\Entity'
                alias: App\Admin\Domain\Entity

        #metadata_cache_driver:
            #    type: pool
            #    pool: doctrine.system_cache_pool
        metadata_cache_driver: ~
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        # Redis
        app: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%"
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
            doctrine.system_cache_pool:
                adapter: cache.adapter.redis