
index:
    path: /
    controller: App\Course\Infrastructure\UI\Controller\Api\IndexController::index

user:
    path: /user
    controller: App\Course\Infrastructure\UI\Controller\Api\UserController::index

courses:
    path: /courses
    controller: App\Course\Infrastructure\UI\Controller\Api\SearchController::index

course-detail:
    path: /courses/{slug}
    controller: App\Course\Infrastructure\UI\Controller\Api\CourseDetailController::index

categories:
    path: /categories
    controller: App\Course\Infrastructure\UI\Controller\Api\CategoryController::index

levels:
    path: /levels
    controller: App\Course\Infrastructure\UI\Controller\Api\LevelController::index
