GET http://api.courses.local:8080/api/courses?level=Básico&priceMin=200&priceMax=400&orderBy=price
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiemlwIjoiREVGIn0..UmEOpsNkJW-n0kwF.pzLy9UorIjZteDw4Y4viGCXu0yCCHBbrHOe-rWwU4Snf0YI.Y5rJKLnCzOEX13DW0i2jxw
###
