version: '3'

services:
  course_php:
    build:
      context: ./php-fpm
    deploy:
      replicas: 3
    volumes:
      - ..:/var/www
    depends_on:
      - database
    networks:
      - course_network

  course_nginx:
    build:
      context: ./nginx
    volumes:
      - ..:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - course_php
    networks:
      - course_network

  database:
    build:
      context: ./database
    container_name: course_database
        #volumes:
      #  - db_course:/var/lib/mysql
      #- ./database/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: course
      MYSQL_USER: devel
      MYSQL_PASSWORD: devel
    networks:
      - course_network

  database_test:
    build:
      context: ./database
    container_name: course_database_test
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: course_test
      MYSQL_USER: devel
      MYSQL_PASSWORD: devel
    networks:
      - course_network

networks:
  course_network:

#volumes:
#  db_course: {}