framework:
    test: true

parameters:
    sourceTruth.path: '%kernel.project_dir%/data/courses_test.txt'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tests\:
        resource: '../tests/'
        exclude:
            - '../tests/bootstrap.php'

    App\Course\Infrastructure\JWT\Encrypt:
        public: true
        arguments:
            - '%jwt.key%'

    App\Course\Infrastructure\JWT\Decrypt:
        public: true
        arguments:
            - '%jwt.key%'
