parameters:
    sourceTruth.path: '%kernel.project_dir%/data/courses_test.txt'

services:

    App\Course\Infrastructure\JWT\Encrypt:
        public: true
        arguments:
            - '%jwt.key%'

    App\Course\Infrastructure\JWT\Decrypt:
        public: true
        arguments:
            - '%jwt.key%'
