
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Course\Infrastructure\UI\Controller\:
        resource: '../../../src/Course/Infrastructure/UI/Controller/' # Hay que poner un ../.. adicional
        tags: ['controller.service_arguments']
