home:
    path: /
    controller: App\Admin\Infrastructure\UI\Controller\HomeController::index

user-new-form:
    path: /user
    controller: App\Admin\Infrastructure\UI\Controller\User\NewController::form
    methods: GET

user-new-save:
    path: /user
    controller: App\Admin\Infrastructure\UI\Controller\User\NewController::form
    methods: POST

user-list:
    path: /user/list
    controller: App\Admin\Infrastructure\UI\Controller\User\ListController::list

user-edit-form:
    path: /user/{id}
    controller: App\Admin\Infrastructure\UI\Controller\User\EditController::form
    methods: GET

user-edit-save:
    path: /user/{id}
    controller: App\Admin\Infrastructure\UI\Controller\User\EditController::form
    methods: POST

user-password-form:
    path: /user/{id}/password
    controller: App\Admin\Infrastructure\UI\Controller\User\EditPasswordController::form
    methods: GET

user-password-save:
    path: /user/{id}/password
    controller: App\Admin\Infrastructure\UI\Controller\User\EditPasswordController::form
    methods: POST

user-delete:
    path: /user/{id}
    controller: App\Admin\Infrastructure\UI\Controller\User\DeleteController::delete
    methods: DELETE

